using Consultation.Domain;
using Consultation.Domain.Enum;
using Consultation.Infrastructure.Data;
using FlutterAPI.ViewModel;

namespace FlutterAPI.Controllers
{
    /// <summary>
    /// Utility controller for creating audit log entries throughout the application
    /// </summary>
    /// <remarks>
    /// This controller provides centralized logging functionality for tracking user actions:
    /// - User authentication events (login, registration)
    /// - Consultation request activities (creation, status changes)
    /// - Dashboard access and navigation tracking
    /// - System administration actions
    /// 
    /// The action logging system supports:
    /// - Security auditing and compliance requirements
    /// - User behavior analytics and system usage tracking
    /// - Troubleshooting and debugging support
    /// - Performance monitoring and optimization insights
    /// 
    /// All logged actions include timestamp, user information, and descriptive messages
    /// for comprehensive system activity tracking.
    /// </remarks>
    public class ActionLogController
    {
        /// <summary>
        /// Creates an action log entry for user activities and system events
        /// </summary>
        /// <param name="message">Descriptive message about the action performed</param>
        /// <param name="AccountName">The account name or identifier of the user performing the action</param>
        /// /// <param name="UserType">The type of user performing the action (Student, Faculty, Adm
        /// /// <param name="user">The user entity associated with the actionram>
        /// <returns>A configured ActionLog entity ready for database persistence</returns>
        /// <remarks>
        /// This static method creates standardized audit log entries with:
        /// 
        /// **Automatic Data Population:**
        /// - Current date and time for accurate timestamping
        /// - User context and account information
        /// - Action description for clear audit trails
        /// 
        /// **Usage Scenarios:**
        /// - **Authentication**: Login/logout events, registration activities
        /// - **Consultation Management**: Request creation, status updates, scheduling
        /// - **Dashboard Activities**: Page access, data retrieval, navigation
        /// - **Administrative Actions**: System configuration, user management
        /// 
        /// **Data Structure:**
        /// - **ActionLogID**: Set to 0 for new entries (auto-generated by database)
        /// - **Date**: Current date when action occurred
        /// - **Time**: Precise time when action was performed
        /// /// - **Description**: Human-readable description of the action
        /// - **Users**: Reference to the user who performed the action
        /// 
        /// **Integration Pattern:**
        /// ```csharp
        /// /// var actio = ActionLogController.ActionLogger(
        ///     "User accessed dashboard", 
        ///     user.Email, 
        ///     UserType.Student, 
        ///     user
        /// );
        /// _context.ActionLog.Add(actionLog);
        /// await _context.SaveChangesAsync();
        /// ```
        /// 
        /// **Security and Compliance:**
        /// - Supports audit requirements for educational systems
        /// - Enables security monitoring and incident response
        /// - Provides data for compliance reporting and analysis
        /// /// - Maintains user activitytory for accountability
        /// </remarks>
        /// <example>
        /// Creating an action log for user login:
        /// <code>
        /// var loginLog = ActionLogController.ActionLogger(
        ///     "User successfully logged in",
        ///     "john.doe@university.edu",
        ///     UserType.Student,
        ///     userEntity
        /// );
        /// </code>
        /// </example>
        public static ActionLog ActionLogger(string message, string AccountName,
            UserType UserType, Users user)
        {
            ActionLog viewModel = new ActionLog()
            {
                ActionLogID = 0,
                Date = DateTime.Now,
                Description = message,
                Time = TimeOnly.FromDateTime(DateTime.Now),
                Users = user
            };
            return viewModel;
        }
    }
}
